"""added Posts table

Revision ID: 49542b816ec9
Revises: 
Create Date: 2025-07-26 22:17:56.695854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49542b816ec9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('post_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post', sa.String(length=200), nullable=True),
    sa.Column('post_comments', sa.String(length=200), nullable=True),
    sa.Column('post_caption', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['gooners.user_id'], ),
    sa.PrimaryKeyConstraint('post_id')
    )
    with op.batch_alter_table('gooners', schema=None) as batch_op:
        batch_op.drop_column('post5')
        batch_op.drop_column('post2')
        batch_op.drop_column('post4')
        batch_op.drop_column('post3')
        batch_op.drop_column('post1')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gooners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post1', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('post3', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('post4', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('post2', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('post5', sa.VARCHAR(length=200), autoincrement=False, nullable=True))

    op.drop_table('posts')
    # ### end Alembic commands ###
