"""Added Comments table

Revision ID: 6a9ca717fd3a
Revises: 49542b816ec9
Create Date: 2025-07-27 11:24:54.408584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a9ca717fd3a'
down_revision = '49542b816ec9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('post_comments')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_comments', sa.VARCHAR(length=200), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
